name: Update RP Stats

on:
  schedule:
    - cron: '*/30 * * * *'  # Toutes les 30 minutes
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Récupérer le repo
        uses: actions/checkout@v3

      - name: Configurer remote pour push
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/AliceRPG/forumactif-rp-stats.git

      - name: Installer Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Installer les dépendances
        run: npm install

      - name: Exécuter le script
        run: node crawler.js

      - name: Commit & push des stats
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add rp-stats.json

          if git diff --cached --quiet; then
            echo "Pas de changement à committer"
            exit 0
          fi

          git commit -m "Mise à jour auto des stats RP"
          git push origin HEAD:master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
